In [1]:
import pandas as pd

```I am formatting osome code for a tutorial```

<!-- hello  -->

In [2]:
df = pd.read_csv("Calcs.csv")

In [3]:
df.head(10)

,"8 Wind 0,Cpi -0.3,+Cpe",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,"9 Wind 0,Cpi -0.3,-Cpe",Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,"23 Wind 270,Cpi 0.2,-Cpe",Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
0,Reference,Zone,Nett Pressure,Area,Applied Load,NaN,Reference,Zone,Nett Pressure,Area,...,Zone,Nett Pressure,Area,Applied Load,NaN,Reference,Zone,Nett Pressure,Area,Applied Load
1,NaN,NaN,[kN/m2],[m2],[kN],NaN,NaN,NaN,[kN/m2],[m2],...,NaN,[kN/m2],[m2],[kN],NaN,NaN,NaN,[kN/m2],[m2],[kN]
2,WI 47,A,-1.488,49,-72.4,NaN,WI 47,A,-1.488,49,...,L,-0.779,65,-50.6,NaN,WI 47,L,-0.779,65,-50.6
3,NaN,B,-0.744,16,-12,NaN,NaN,B,-0.744,16,...,A,-1.779,63,-111.6,NaN,WI 46,A,-1.779,63,-111.6
4,WI 46,L,-0.317,483,-153.2,NaN,WI 46,L,-0.317,483,...,B,-1.186,293,-347.4,NaN,NaN,B,-1.186,293,-347.4
5,WI 54,W,1.711,35,60.4,NaN,WI 54,W,1.711,35,...,C,-0.83,128,-106,NaN,NaN,C,-0.83,128,-106
6,WI 43,B,-0.744,195,-144.8,NaN,WI 43,B,-0.744,195,...,L,-0.779,35,-27.5,NaN,WI 54,L,-0.779,35,-27.5
7,NaN,C,-0.298,324,-96.5,NaN,NaN,C,-0.298,324,...,W,0.54,519,280.2,NaN,WI 43,W,0.54,519,280.2
8,WI 44,W,1.823,483,881.1,NaN,WI 44,W,1.823,483,...,A,-1.779,63,-111.6,NaN,WI 44,A,-1.779,63,-111.6
9,WI 45,B,-0.744,195,-144.8,NaN,WI 45,B,-0.744,195,...,B,-1.186,293,-347.4,NaN,NaN,B,-1.186,293,-347.4

In [4]:

df1 = pd.read_csv("Strength.csv",header = 6, 
usecols=[0,6,7,8,9,10,11],
na_values="-"
)
df1.rename(columns={"Unnamed: 0": "Support", "Fvert\n[kN]":"Fv", "Fmajor\n[kN]":"Fy","Fminor\n[kN]":"Fx","Mmajor\n[kNm]":"My","Mminor\n[kNm]":"Mx","Mtor\n[kNm]":"Mtor"}, inplace=True)
df1.Support = df1.Support.fillna(0)


df1

                  Support    Fv    Fy    Fx   My   Mx  Mtor
0                 SUP 1/A  24.6  49.6  27.3  0.0  0.0   0.0
1                       0  -8.4 -29.5 -22.5  0.0  0.0   0.0
2                 SUP 1/B  23.7  43.3  12.4  0.0  0.0   0.0
3                       0  -9.1 -29.5 -25.7  0.0  0.0   0.0
4                 SUP 1/J  23.7  49.6  25.7  0.0  0.0   0.0
..                    ...   ...   ...   ...  ...  ...   ...
95  No results available.   NaN   NaN   NaN  NaN  NaN   NaN
96                      0   NaN   NaN   NaN  NaN  NaN   NaN
97          Core Supports   NaN   NaN   NaN  NaN  NaN   NaN
98  No results available.   NaN   NaN   NaN  NaN  NaN   NaN
99                      0   NaN   NaN   NaN  NaN  NaN   NaN

[100 rows x 7 columns]

In [5]:
# Everytime row in "Support" = NaN, row = [i-1,'Support'] -> if 

# df1.Support = NaN, df1 = df1[i-1,'Support']
for i in range (1,len(df1)):
    if df1.loc[i, 'Support'] == 0:
        df1.loc[i, 'Support'] = df1.loc[i-1, 'Support'] 

df1.set_index('Support', inplace=True)
df1.head()

# Finding maximum value for each column, make new table with the values and show what support is associated with it 
max_index = df1.Fv.idxmax()
print(max_index)
index_list = []
for column in df1.columns:
    print(column)
    if column == 'Fv':
        index_list.append((column,df1[column].idxmin(),df1[column].min()))
    else:
        index_list.append((column,df1[column].abs().idxmax(),df1[column].abs().max()))
    
    

df1.columns
index_list

SUP J/#628
Fv
Fy
Fx
My
Mx
Mtor

[('Fv', 'SUP I/#608', -630.2),
 ('Fy', 'SUP C/#548', 211.9),
 ('Fx', 'SUP J/#627', 224.1),
 ('My', 'SUP 1/A', 0.0),
 ('Mx', 'SUP 1/A', 0.0),
 ('Mtor', 'SUP A/#302', 0.2)]

In [6]:
summary_df = pd.DataFrame()
for entry in index_list:
    tempdf = df1.loc[entry[1]]
    summary_df = summary_df.append(tempdf)
# summary_df.append(tempdf)
summary_df

               Fv     Fy     Fx   My   Mx  Mtor
Support
SUP I/#608  643.0  169.3   47.6  0.0  0.0   0.2
SUP I/#608 -630.2 -165.1  -74.5  0.0  0.0  -0.1
SUP C/#548  674.8  211.9    0.4  0.0  0.0   0.2
SUP C/#548 -193.3 -165.1   -0.5  0.0  0.0  -0.2
SUP J/#627  708.4  159.9  224.1  0.0  0.0   0.1
SUP J/#627 -263.3  -59.4 -128.1  0.0  0.0  -0.2
SUP 1/A      24.6   49.6   27.3  0.0  0.0   0.0
SUP 1/A      -8.4  -29.5  -22.5  0.0  0.0   0.0
SUP 1/A      24.6   49.6   27.3  0.0  0.0   0.0
SUP 1/A      -8.4  -29.5  -22.5  0.0  0.0   0.0
SUP A/#302   98.0   30.0   68.1  0.0  0.0   0.2
SUP A/#302  -23.4  -23.8  -60.4  0.0  0.0  -0.2

In [7]:
# Finding maximum service load combinations for foundation design 
# df3=pd.read_csv("Service.csv", encoding ='latin1',header = 6, 
# usecols=[0,4,5,6,7,8,9,10],
# na_values="-"
# )
# df3.rename(columns={"Unnamed: 0": "Support","Unnamed: 4": "Loadcase", "Fvert\n[kN]":"Fv", "Fmajor\n[kN]":"Fy","Fminor\n[kN]":"Fx","Mmajor\n[kNm]":"My","Mminor\n[kNm]":"Mx","Mtor\n[kNm]":"Mtor"}, inplace=True)
df3=pd.read_csv("Service.csv", encoding ='latin1',header = 6, 
usecols=[0,5,6,7,8,9,10],
na_values="-"
)
df3.rename(columns={"Unnamed: 0": "Support", "Fvert\n[kN]":"Fv", "Fmajor\n[kN]":"Fy","Fminor\n[kN]":"Fx","Mmajor\n[kNm]":"My","Mminor\n[kNm]":"Mx","Mtor\n[kNm]":"Mtor"}, inplace=True)

# Creating support names for all loadcases
df3.Support = df3.Support.fillna(0)
for i in range (1,len(df3)):
    if df3.loc[i, 'Support'] == 0:
        df3.loc[i, 'Support'] = df3.loc[i-1, 'Support'] 

df3.set_index('Support', inplace=True)

# Finding maximum value for each column, make new table with the values and show what support is associated with it 
max_index = df3.Fv.idxmax()
print(max_index)
index_list = []
for column in df3.columns:
    print(column)
    if column == 'Fv':
        index_list.append((column,df3[column].idxmin(),df3[column].min()))
    # if column == 'Fy','Fx','My','Mx','Mtor':
    else:
        index_list.append((column,df3[column].abs().idxmax(),df3[column].abs().max()))
    
    


summary_df3 = pd.DataFrame()
for entry in index_list:
    tempdf = df3.loc[entry[1]]
    summary_df3 = summary_df3.append(tempdf)
# summary_df.append(tempdf)
summary_df3.head(30)

PF2
Fv
Fy
Fx
My
Mx
Mtor

            Fv    Fy    Fx   My   Mx  Mtor
Support
PF3      184.2  61.0   5.3  0.0  0.0   0.0
PF3      173.0  60.9   3.8  0.0  0.0   0.0
PF3      195.4  61.0   6.9  0.0  0.0   0.0
PF3      183.6  60.1   5.3  0.0  0.0   0.0
PF3      184.8  61.8   5.3  0.0  0.0   0.0
PF3      254.1  91.1   7.5  0.0  0.0   0.0
PF3      238.4  91.0   5.4  0.0  0.0   0.0
PF3      269.7  91.3   9.7  0.0  0.0   0.0
PF3      253.2  89.9   7.5  0.0  0.0   0.0
PF3      254.9  92.4   7.6  0.0  0.0   0.0
PF3      172.4  55.9   5.0  0.0  0.0   0.0
PF3      228.3  80.0   6.7  0.0  0.0   0.0
PF3      125.2  35.5   3.5  0.0  0.0   0.0
PF3      184.2  61.0   5.3  0.0  0.0   0.0
PF3      173.0  60.9   3.8  0.0  0.0   0.0
PF3      195.4  61.0   6.9  0.0  0.0   0.0
PF3      183.6  60.1   5.3  0.0  0.0   0.0
PF3      184.8  61.8   5.3  0.0  0.0   0.0
PF3      254.1  91.1   7.5  0.0  0.0   0.0
PF3      238.4  91.0   5.4  0.0  0.0   0.0
PF3      269.7  91.3   9.7  0.0  0.0   0.0
PF3      253.2  89.9   7.5  0.0  0.0   0.0
PF3      254.9  92.4   7.6  0.0  0.0   0.0
PF3      172.4  55.9   5.0  0.0  0.0   0.0
PF3      -67.5  81.5 -33.2  0.0  0.0   0.0
PF3     -174.1  36.3 -36.6  0.0  0.0   0.0
PF3     -152.6  66.2 -36.3  0.0  0.0   0.1
PF3     -259.2  21.0 -39.6  0.0  0.0   0.1
PF3      132.2 -37.3   3.1  0.0  0.0   0.0
PF3       71.1 -44.5   1.2  0.0  0.0   0.0